Revert r39048: (circular-deferred-6164-2) introduced pyflakes warnings
    twisted/test/test_defer.py:916: redefinition of unused 'warnings' from line 10

Reopens: #6164

git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@39072 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb