Revert r35404 - Python 2.6 test suite regressions
A bunch of failures like these:

exceptions.AttributeError: FilePathTestCase object has no attribute addCleanup

Reopens: #5903



git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@35408 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb