Revert r33835 - Windows test suite regression
Reopens: #5524

The new tests fail on Windows:

[ERROR]
Traceback (most recent call last):
  File "c:\bot-glyph-5\winxp32-py2.5-select\Twisted\twisted\names\test\test_tap.py", line 94, in test_recursiveConfiguration
    x.resolvers[-1]._parseCall.cancel()
  File "c:\bot-glyph-5\winxp32-py2.5-select\Twisted\twisted\names\root.py", line 431, in __getattr__
    raise AttributeError(name)
exceptions.AttributeError: _parseCall

twisted.names.test.test_tap.OptionsTests.test_recursiveConfiguration


git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@33880 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb