Revert r19657 - test suite regression on win32
Numerous test_runner tests fail on win32 in roughly this way:

{{{
[ERROR]: twisted.trial.test.test_runner.TestTrialRunner.test_logFileGetsClosed

Traceback (most recent call last):
  File "c:\twistedbuildbot\W32-full2.4-scmikes-select\Twisted\twisted\trial\test\test_runner.py", line 154, in test_logFileGetsClosed
    self.runner.run(self.test)
  File "c:\twistedbuildbot\W32-full2.4-scmikes-select\Twisted\twisted\trial\runner.py", line 791, in run
    oldDir = self._setUpTestdir()
  File "c:\twistedbuildbot\W32-full2.4-scmikes-select\Twisted\twisted\trial\runner.py", line 701, in _setUpTestdir
    os.path.abspath("_trial_temp_old%s"
exceptions.OSError: [Errno 13] Permission denied
}}}


git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@19662 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb