Skip SSHCheckerTests on Windows
The Windows builds are failing with this message:

    [ERROR]
    Traceback (most recent call last):
      File "D:\a\1\s\.tox\alldeps-withcov-windows\lib\site-packages\twisted\cred\test\test_strcred.py", line 434, in test_isChecker
        sshChecker = strcred.makeChecker("sshkey")
      File "D:\a\1\s\.tox\alldeps-withcov-windows\lib\site-packages\twisted\cred\strcred.py", line 117, in makeChecker
        return findCheckerFactory(authType).generateChecker(argstring)
      File "D:\a\1\s\.tox\alldeps-withcov-windows\lib\site-packages\twisted\plugins\cred_sshkeys.py", line 42, in generateChecker
        return SSHPublicKeyChecker(UNIXAuthorizedKeysFiles())
      File "D:\a\1\s\.tox\alldeps-withcov-windows\lib\site-packages\twisted\conch\checkers.py", line 527, in __init__
        raise ValueError("No pwd module found, and no userdb argument passed.")
    builtins.ValueError: No pwd module found, and no userdb argument passed.

    twisted.cred.test.test_strcred.SSHCheckerTests.test_isChecker

This exception was introduced in this PR. Previous to this PR the
UNIXAuthorizedKeysFiles initializer would allow self.userdb to be None
and generate an AttributeError later when attempting to get authorized
keys.