Potential race condition in _startRunCallbacks
When creating a Deferred in a separate thread, then chaining that deferred into the callback chain of another Deferred, and then adding that deferred to a DeferredList to wait for completion, _runCallbacks can be executed on the chained deferred before the result has been set. This change seems to prevent that issue. I've attached some example code and an example traceback of the error. 

"""
#!/usr/bin/env python

from time import sleep
from queue import Queue
from twisted.internet import reactor
from twisted.internet.defer import Deferred, succeed, gatherResults
from twisted.internet.task import LoopingCall
from twisted.python import log

import logging
logging.basicConfig()

observer = log.PythonLoggingObserver(loggerName="testfile")
observer.start()


def t():
    q = Queue()

    def p():
        sleep(0.0001)
        return succeed(None)

    def f(*a, **kw):
        d = Deferred()
        q.put(d)
        return p().chainDeferred(d)

    for i in xrange(4):
        reactor.callInThread(f)

    return gatherResults([q.get() for _ in xrange(4)], consumeErrors=True)

if __name__ == "__main__":
    l = LoopingCall(reactor.callInThread, t)
    l.start(0.005, now=True)
    reactor.run()
"""

"""
CRITICAL:testfile:Unhandled Error
Traceback (most recent call last):
  File "/home/zach/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/zach/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/zach/anaconda2/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/home/zach/anaconda2/lib/python2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/home/zach/anaconda2/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/zach/anaconda2/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/zach/anaconda2/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/zach/anaconda2/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "./testfile.py", line 32, in t
    return gatherResults([q.get() for _ in xrange(4)], consumeErrors=True)
  File "/home/zach/anaconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 1182, in gatherResults
    consumeErrors=consumeErrors)
  File "/home/zach/anaconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 1100, in __init__
    errbackArgs=(index,FAILURE))
  File "/home/zach/anaconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/home/zach/anaconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 629, in _runCallbacks
    isinstance(current.result, failure.Failure)]
exceptions.AttributeError: Deferred instance has no attribute 'result'
"""